// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZi1EB0-hCRodUeyFutWOg2eFv1jJYnlo',
    appId: '1:768960404529:web:0bd9c3a0b7d2a50d27c910',
    messagingSenderId: '768960404529',
    projectId: 'task-app-73749',
    authDomain: 'task-app-73749.firebaseapp.com',
    storageBucket: 'task-app-73749.firebasestorage.app',
    measurementId: 'G-Q7JE4ZE5CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWhr5fwqvmN3WpFZ1B1xDflN9vSMcRho',
    appId: '1:768960404529:android:e327d8b4528f47b627c910',
    messagingSenderId: '768960404529',
    projectId: 'task-app-73749',
    storageBucket: 'task-app-73749.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCihV5h59S8mzO4rCxCCBW2_4laZlGN5wI',
    appId: '1:768960404529:ios:0e6c9d39f0a6b26927c910',
    messagingSenderId: '768960404529',
    projectId: 'task-app-73749',
    storageBucket: 'task-app-73749.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCihV5h59S8mzO4rCxCCBW2_4laZlGN5wI',
    appId: '1:768960404529:ios:0e6c9d39f0a6b26927c910',
    messagingSenderId: '768960404529',
    projectId: 'task-app-73749',
    storageBucket: 'task-app-73749.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZi1EB0-hCRodUeyFutWOg2eFv1jJYnlo',
    appId: '1:768960404529:web:89df24477dba683627c910',
    messagingSenderId: '768960404529',
    projectId: 'task-app-73749',
    authDomain: 'task-app-73749.firebaseapp.com',
    storageBucket: 'task-app-73749.firebasestorage.app',
    measurementId: 'G-VMJ3RWYP1S',
  );
}
